# Data Preprocessing Tools

## Importing the libraries

In [ ]:
#1. for working with arrays
import numpy as np
#2. module pyplot of matplotlib library for plotting graphs
import matplotlib.pyplot as plt
#3. for importing datasets:
import pandas as pd

## Importing the dataset

In [5]:
#create new variable dataset that stores data frame of dataset
dataset=pd.read_csv('Data.csv')
#2more steps-create matrix of features:x & dependent variable vector:y
#for matrix of features- take all rows but do not take last col
X=dataset.iloc[:,:-1].values
#for dependent variable vector -take all rows & only last col
y=dataset.iloc[:,-1].values

# do not forget to import Data.csv file!!

In [6]:
#print the matrix of features
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
#print the dependent variable vector
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [8]:
# Identify missing data (assumes that missing data is represented as NaN)
missing_data=dataset.isnull().sum()
# Print the number of missing entries in each column
print("Missing data: \n",missing_data)

Missing data: 
 Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


In [9]:
#import library imputer
from sklearn.impute import SimpleImputer
#create object: imputer of this class SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

#apply fit method
# columns->missing values wale
imputer.fit(X[:,1:3])
#apply transform method- also it returns so update
X[:,1:3]=imputer.transform(X[:,1:3])


In [10]:
#print updated valyue of matrix of features after updating missing values colm
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [11]:
#import 2 classes
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#create object of ColumnTransformer
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

# transforms the country into binary vector form of 000,010,100 etc

In [12]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [13]:
from sklearn.preprocessing import LabelEncoder
#create object of label encoder
le=LabelEncoder()
y=le.fit_transform(y)
# contains only yes/no so convert into 0/1

In [14]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [16]:
# training:80%
# test:20%
#import module train_test_split from scikit learn library
from sklearn.model_selection import train_test_split
#it will return 4 sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [17]:
print(X_train)
# out of 10 entries->80%= 8 values in training set

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [18]:
print(X_test)
# out of 10 entries-> 20% in testing ie 2 values

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [21]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [22]:
print(y_test)

[0 1]


## Feature Scaling

In [23]:
# larger values must not overpower smaller ones so have a same scale for all the values using feature scaling
# 2 types: normalization & standardization
# we use standardization ie value-mean/standard deviation
# it returns values in a range of [-3,3]

#import library for standardization- standard scaler
from sklearn.preprocessing import StandardScaler
#create object:
sc=StandardScaler()
#apply on X train&test
# on the new X_train and X_test dataset check columns that need to be normalized---> must contain numerical data
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:]) #not fit only transform

In [24]:
# it returns values in a range of {-2,2}
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [25]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
